services:
  
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    container_name: ${APP_NAME}.mysql
    image: mariadb:latest
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: mysqladmin -uwp_user -pwp_pass ping -h 127.0.0.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  
  wordpress:
    image: wordpress:latest
    container_name: ${APP_NAME}.wp
    volumes:
      - wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - 80:80
    depends_on:
      - db
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: ${APP_NAME}.phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - 8082:80

volumes:
  database:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./src
